services:
  cat-app:
    image: certificateauthenticationtest
    build:
      context: .
      dockerfile: CertificateAuthenticationTest/Dockerfile
    environment:
      Logging__LogLevel__Default: Trace
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/server.crt:/root/ssl/server.crt
      - ./nginx/ca.crt:/root/ssl/ca.crt
    ports:
      - "443:443"
    depends_on:
      - cat-app
